version: "3"
services:
  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - backend/.env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    links:
      - backend
    environment:
      - API_HOST=http://backend
    ports:
      - "3000:3000"
