apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  name: {{ include "awe-boilerplate.fullname" . }}-backend
  labels:
    app: backend
    {{- include "awe-boilerplate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.BackEnd.replicaCount }}
  selector:
    matchLabels:
      app: backend
      {{- include "awe-boilerplate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: backend
        {{- include "awe-boilerplate.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: "{{ .Values.BackEnd.image.repository }}:{{ .Values.BackEnd.image.tag }}"
          imagePullPolicy: {{ .Values.BackEnd.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ include "awe-boilerplate.fullname" . }}-cfg
