apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "awe-boilerplate.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "awe-boilerplate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.FrontEnd.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      {{- include "awe-boilerplate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: frontend
        {{- include "awe-boilerplate.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.FrontEnd.image.repository }}:{{ .Values.FrontEnd.image.tag }}"
          imagePullPolicy: {{ .Values.FrontEnd.image.pullPolicy }}
          env:
            - name: API_HOST
              value: "https://{{ .Values.BackEnd.domain }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
