apiVersion: v1
kind: Service
metadata:
  name: {{ include "awe-boilerplate.fullname" . }}-db
  labels:
    app: db
    {{- include "awe-boilerplate.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: db
    {{- include "awe-boilerplate.selectorLabels" . | nindent 4 }}
