apiVersion: v1
kind: Service
metadata:
  name: {{ include "awe-boilerplate.fullname" . }}-frontend
  labels:
    app: frontend
    {{- include "awe-boilerplate.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: frontend
    {{- include "awe-boilerplate.selectorLabels" . | nindent 4 }}
