# Default values for awe-boilerplate.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


FrontEnd:
  replicaCount: 1
  domain: "local"
  image:
    repository: eu.gcr.io/mind-blowing-company/mind-blowing-company/awesome-boilerplate-frontend
    tag: master
    pullPolicy: Always #IfNotPresent

BackEnd:
  replicaCount: 1
  domain: "api.local"
  image:
    repository: eu.gcr.io/mind-blowing-company/mind-blowing-company/awesome-boilerplate-backend
    tag: master
    pullPolicy: Always #IfNotPresent


imagePullSecrets: [ name: "gcr-json-key" ]
